api = "0.6"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"
  id = "paketo-buildpacks/dotnet-core-aspnet"
  name = "Paketo ASP.NET Core Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:3.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-03T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-aspnetcore@3.1.20?checksum=2ab7dee30c90bee56c35ef9c1bde43edf7e131cf7236a870eed75b85603bae2c&download_url=https://download.visualstudio.microsoft.com/download/pr/63827c97-af9b-4c3b-a9df-5ed97c51cbe1/e07ed23d466369c90c96340c882f08fe/aspnetcore-runtime-3.1.20-linux-x64.tar.gz"
    sha256 = "0ea6a59dad1025ac6d42d3cbfffbb3a575748a50b5500f392c9a6b4f0a5a891b"
    source = "https://download.visualstudio.microsoft.com/download/pr/63827c97-af9b-4c3b-a9df-5ed97c51cbe1/e07ed23d466369c90c96340c882f08fe/aspnetcore-runtime-3.1.20-linux-x64.tar.gz"
    source_sha256 = "2ab7dee30c90bee56c35ef9c1bde43edf7e131cf7236a870eed75b85603bae2c"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_3.1.20_linux_x64_bionic_0ea6a59d.tar.xz"
    version = "3.1.20"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:3.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-03T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-aspnetcore@3.1.21?checksum=02692dddac6dbd306472eb81678624992f36e85a5deca34fb6d5e3c18d5f639f&download_url=https://download.visualstudio.microsoft.com/download/pr/c4565012-97e8-4a5a-9edf-8d6c94f0ac5c/dd227c01d532bcb731b026243a51f55f/aspnetcore-runtime-3.1.21-linux-x64.tar.gz"
    sha256 = "5f998fa7f7ef5208ab51aba3e88bff42435238dd46f88b0452b39786ab36f8e4"
    source = "https://download.visualstudio.microsoft.com/download/pr/c4565012-97e8-4a5a-9edf-8d6c94f0ac5c/dd227c01d532bcb731b026243a51f55f/aspnetcore-runtime-3.1.21-linux-x64.tar.gz"
    source_sha256 = "02692dddac6dbd306472eb81678624992f36e85a5deca34fb6d5e3c18d5f639f"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_3.1.21_linux_x64_bionic_5f998fa7.tar.xz"
    version = "3.1.21"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:5.0:*:*:*:*:*:*:*"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-aspnetcore@5.0.11?checksum=e8afced6086cf8806ac286467957d4a600807821875d46c6075f8f6b32735179&download_url=https://download.visualstudio.microsoft.com/download/pr/ac2cec9e-f5ab-44db-8fa9-aba5e5cf7378/956dac1b6510675a0ae8705918e22df7/aspnetcore-runtime-5.0.11-linux-x64.tar.gz"
    sha256 = "2b9c38604d2bdaaa244656d01bb7f21f192f7e8dc749a9bb61ca87e9c0336031"
    source = "https://download.visualstudio.microsoft.com/download/pr/ac2cec9e-f5ab-44db-8fa9-aba5e5cf7378/956dac1b6510675a0ae8705918e22df7/aspnetcore-runtime-5.0.11-linux-x64.tar.gz"
    source_sha256 = "e8afced6086cf8806ac286467957d4a600807821875d46c6075f8f6b32735179"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_5.0.11_linux_x64_bionic_2b9c3860.tar.xz"
    version = "5.0.11"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:5.0:*:*:*:*:*:*:*"
    deprecation_date = "2022-05-08T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-aspnetcore@5.0.12?checksum=ea97d8c86178c3d29fafc485013267ac3801cdd275ac7653b3b95d087ff5e530&download_url=https://download.visualstudio.microsoft.com/download/pr/ad0a54ca-4b88-4762-a790-aebeaba6b9e7/0f796fb90696d078046d90d8a05c027e/aspnetcore-runtime-5.0.12-linux-x64.tar.gz"
    sha256 = "76e02f419bdc9fbe11aeb6f268fb27d265adde5431df8eb8710d5c3c6a403580"
    source = "https://download.visualstudio.microsoft.com/download/pr/ad0a54ca-4b88-4762-a790-aebeaba6b9e7/0f796fb90696d078046d90d8a05c027e/aspnetcore-runtime-5.0.12-linux-x64.tar.gz"
    source_sha256 = "ea97d8c86178c3d29fafc485013267ac3801cdd275ac7653b3b95d087ff5e530"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_5.0.12_linux_x64_bionic_76e02f41.tar.xz"
    version = "5.0.12"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-aspnetcore"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "5.0.*"
    id = "dotnet-aspnetcore"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
