api = "0.8"

[buildpack]
  description = "A buildpack for installing the appropriate .NET Core ASP.NET version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"
  id = "paketo-buildpacks/dotnet-core-aspnet"
  keywords = ["dotnet", "ASP.NET"]
  name = "Paketo Buildpack for ASP.NET Core"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-aspnet/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:3.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@3.1.30?checksum=92e8e028d9a6094437a38ba2d3a7898436f027ccd2655ca52b2b0b27e42e3455&download_url=https://download.visualstudio.microsoft.com/download/pr/12f61df9-e5d2-4cc2-b992-80d30ee3fc43/0087f4e0b8b3a94effa890ee3ebba0b1/aspnetcore-runtime-3.1.30-linux-x64.tar.gz"
    sha256 = "8832421ba6308e392ca9540a02ab3049fbeb74523d3403a1479808efe01624b0"
    source = "https://download.visualstudio.microsoft.com/download/pr/12f61df9-e5d2-4cc2-b992-80d30ee3fc43/0087f4e0b8b3a94effa890ee3ebba0b1/aspnetcore-runtime-3.1.30-linux-x64.tar.gz"
    source_sha256 = "92e8e028d9a6094437a38ba2d3a7898436f027ccd2655ca52b2b0b27e42e3455"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_3.1.30_linux_x64_bionic_8832421b.tar.xz"
    version = "3.1.30"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:3.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@3.1.31?checksum=0504d12d01a66f58d7d919f0af76957bcf6e997d2691a71ede83de079b7ab70c&download_url=https://download.visualstudio.microsoft.com/download/pr/2fc0069c-e99a-4296-99ee-a422b3cf50de/df8aee91eeaf50a12c810c3845341eb3/aspnetcore-runtime-3.1.31-linux-x64.tar.gz"
    sha256 = "fe1b102f5b269e998630e330d00b6dc911e802b441d5d6d6fd4daa17e2a18aab"
    source = "https://download.visualstudio.microsoft.com/download/pr/2fc0069c-e99a-4296-99ee-a422b3cf50de/df8aee91eeaf50a12c810c3845341eb3/aspnetcore-runtime-3.1.31-linux-x64.tar.gz"
    source_sha256 = "0504d12d01a66f58d7d919f0af76957bcf6e997d2691a71ede83de079b7ab70c"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_3.1.31_linux_x64_bionic_fe1b102f.tar.xz"
    version = "3.1.31"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:6.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@6.0.10?checksum=17685d3e8fa7aa9c1a658f7ca5e176bec7bb4c189b0352ac5abfed98135b93d9&download_url=https://download.visualstudio.microsoft.com/download/pr/7d44ddeb-ad35-41a8-a581-03b151afbd80/6888586c28836b1e1f71df879184550b/aspnetcore-runtime-6.0.10-linux-x64.tar.gz"
    sha256 = "6d47537780c728d3775c9afc03fba25423e9c74c937f436c2700bbfb68f88ff7"
    source = "https://download.visualstudio.microsoft.com/download/pr/7d44ddeb-ad35-41a8-a581-03b151afbd80/6888586c28836b1e1f71df879184550b/aspnetcore-runtime-6.0.10-linux-x64.tar.gz"
    source_sha256 = "17685d3e8fa7aa9c1a658f7ca5e176bec7bb4c189b0352ac5abfed98135b93d9"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_6.0.10_linux_x64_bionic_6d475377.tar.xz"
    version = "6.0.10"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:6.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@6.0.11?checksum=d499a4af84cc3f9947230392f10d5af5fda65a71e002554f2ea3cd4244538133&download_url=https://download.visualstudio.microsoft.com/download/pr/0a17a9f6-7705-4b47-aead-c0b582cad317/158b62e5183281e416994d56ce81bc0c/aspnetcore-runtime-6.0.11-linux-x64.tar.gz"
    sha256 = "6410755564f1e4bb9dd5f26d8fb2f7804f964caf7d48e9b692477a684a8be3a2"
    source = "https://download.visualstudio.microsoft.com/download/pr/0a17a9f6-7705-4b47-aead-c0b582cad317/158b62e5183281e416994d56ce81bc0c/aspnetcore-runtime-6.0.11-linux-x64.tar.gz"
    source_sha256 = "d499a4af84cc3f9947230392f10d5af5fda65a71e002554f2ea3cd4244538133"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_6.0.11_linux_x64_bionic_64107555.tar.xz"
    version = "6.0.11"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:7.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-05-14T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@7.0.0?checksum=27753c368cc075e23fe2c23063be252f54d19194a004b178b4faab1ba2e8af8d&download_url=https://download.visualstudio.microsoft.com/download/pr/4bbb4d31-70ba-4def-b747-4358be873982/3dbca5b64c2ffb88641c0e42bdeb297a/aspnetcore-runtime-7.0.0-linux-x64.tar.gz"
    sha256 = "4ed44c14ddfe35a19f7744a7d9b9e4e78f697734bad8f2cea8cc5473ffb96f48"
    source = "https://download.visualstudio.microsoft.com/download/pr/4bbb4d31-70ba-4def-b747-4358be873982/3dbca5b64c2ffb88641c0e42bdeb297a/aspnetcore-runtime-7.0.0-linux-x64.tar.gz"
    source_sha256 = "27753c368cc075e23fe2c23063be252f54d19194a004b178b4faab1ba2e8af8d"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_7.0.0_linux_x64_bionic_4ed44c14.tar.xz"
    version = "7.0.0"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-aspnetcore"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "6.0.*"
    id = "dotnet-aspnetcore"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "7.0.*"
    id = "dotnet-aspnetcore"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
