api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"
  id = "paketo-buildpacks/dotnet-core-aspnet"
  name = "Paketo ASP.NET Core Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:3.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-03T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-aspnetcore@3.1.18?checksum=0eacc6ed1a979c1758aab42c2186321348af2a6ae43d185888a44782cc724c05&download_url=https://download.visualstudio.microsoft.com/download/pr/67843ba3-26f9-4746-bdfe-0f8074c00767/d51340f4f5cf8a361414650f510fe202/aspnetcore-runtime-3.1.18-linux-x64.tar.gz"
    sha256 = "f089debab0dce7509a4d59c4516571b0fea97691f30785e414026c959aa5d631"
    source = "https://download.visualstudio.microsoft.com/download/pr/67843ba3-26f9-4746-bdfe-0f8074c00767/d51340f4f5cf8a361414650f510fe202/aspnetcore-runtime-3.1.18-linux-x64.tar.gz"
    source_sha256 = "0eacc6ed1a979c1758aab42c2186321348af2a6ae43d185888a44782cc724c05"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_3.1.18_linux_x64_bionic_f089deba.tar.xz"
    version = "3.1.18"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:3.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-03T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-aspnetcore@3.1.19?checksum=94714eda77734e751e31a352e5c7f10bbdfce82285a11d513cf6ac6b71a36a2a&download_url=https://download.visualstudio.microsoft.com/download/pr/7a050aa5-7842-4bfa-a1c9-67c6c5995ea9/5592f443610943d5ca738ae92309dfab/aspnetcore-runtime-3.1.19-linux-x64.tar.gz"
    sha256 = "7e85e0360a9fde63cd867f93ed23d309bcc12a37f7020a9bdc8c04c3986ec966"
    source = "https://download.visualstudio.microsoft.com/download/pr/7a050aa5-7842-4bfa-a1c9-67c6c5995ea9/5592f443610943d5ca738ae92309dfab/aspnetcore-runtime-3.1.19-linux-x64.tar.gz"
    source_sha256 = "94714eda77734e751e31a352e5c7f10bbdfce82285a11d513cf6ac6b71a36a2a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_3.1.19_linux_x64_bionic_7e85e036.tar.xz"
    version = "3.1.19"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:5.0:*:*:*:*:*:*:*"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-aspnetcore@5.0.9?checksum=b6cba668bf18981d2274d093a7acaedcd06fbf1929c864650f22f3cf3313481c&download_url=https://download.visualstudio.microsoft.com/download/pr/19046594-e911-4784-a148-6de3d74d4a7f/d5c1ba792c4266a2d2a8eea41e81a060/aspnetcore-runtime-5.0.9-linux-x64.tar.gz"
    sha256 = "1f2145b038777e1452b3707a24e016dcda16c0623f7e42df321dee89f4d7a2cc"
    source = "https://download.visualstudio.microsoft.com/download/pr/19046594-e911-4784-a148-6de3d74d4a7f/d5c1ba792c4266a2d2a8eea41e81a060/aspnetcore-runtime-5.0.9-linux-x64.tar.gz"
    source_sha256 = "b6cba668bf18981d2274d093a7acaedcd06fbf1929c864650f22f3cf3313481c"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_5.0.9_linux_x64_bionic_1f2145b0.tar.xz"
    version = "5.0.9"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:5.0:*:*:*:*:*:*:*"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    purl = "pkg:generic/dotnet-aspnetcore@5.0.10?checksum=a8dc98bcb8e2898056e5a77f0d62527ac66fe3207c81d3ab6b08c979381a5fd5&download_url=https://download.visualstudio.microsoft.com/download/pr/20984ce7-f18d-414a-9a16-bf05cd0cc7a1/ca5ab821884e7e3b3b4febf9f7a4b50e/aspnetcore-runtime-5.0.10-linux-x64.tar.gz"
    sha256 = "947ce6055ab6ed2cc7866683ad0b3e263bc35eb879a49352463616a1c5b7528f"
    source = "https://download.visualstudio.microsoft.com/download/pr/20984ce7-f18d-414a-9a16-bf05cd0cc7a1/ca5ab821884e7e3b3b4febf9f7a4b50e/aspnetcore-runtime-5.0.10-linux-x64.tar.gz"
    source_sha256 = "a8dc98bcb8e2898056e5a77f0d62527ac66fe3207c81d3ab6b08c979381a5fd5"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_5.0.10_linux_x64_bionic_947ce605.tar.xz"
    version = "5.0.10"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-aspnetcore"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "5.0.*"
    id = "dotnet-aspnetcore"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
