api = "0.8"

[buildpack]
  description = "A buildpack for installing the appropriate .NET Core ASP.NET version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"
  id = "paketo-buildpacks/dotnet-core-aspnet"
  keywords = ["dotnet", "ASP.NET"]
  name = "Paketo ASP.NET Core Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-aspnet/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:3.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@3.1.26?checksum=bbf42127f6c58fe6d02205b7ede4962cf10681a274bbf569d27f7e1e2b153e66&download_url=https://download.visualstudio.microsoft.com/download/pr/6f72adf7-0e78-48ea-85ef-e72a39a1f8a1/1ec0238c236c3757e5628563a329fdc4/aspnetcore-runtime-3.1.26-linux-x64.tar.gz"
    sha256 = "ac024ff660da7f046b9605ff9911851cd91a91f016aaf6ab67fb15efb249f559"
    source = "https://download.visualstudio.microsoft.com/download/pr/6f72adf7-0e78-48ea-85ef-e72a39a1f8a1/1ec0238c236c3757e5628563a329fdc4/aspnetcore-runtime-3.1.26-linux-x64.tar.gz"
    source_sha256 = "bbf42127f6c58fe6d02205b7ede4962cf10681a274bbf569d27f7e1e2b153e66"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_3.1.26_linux_x64_bionic_ac024ff6.tar.xz"
    version = "3.1.26"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:3.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@3.1.27?checksum=8fc95f7e66168a9ee9fb662c971c61264858e9b0c7aedd8e93b7b1f6fa0a5ed3&download_url=https://download.visualstudio.microsoft.com/download/pr/a1d2cc21-97e0-45a6-8e56-419468d6029f/bd71225f2b7dad7dc44272d303276e7f/aspnetcore-runtime-3.1.27-linux-x64.tar.gz"
    sha256 = "89c395e6fb0ea757d7bbf9258f1a48c2719de69c1d2815bf13dd0bbf940ea543"
    source = "https://download.visualstudio.microsoft.com/download/pr/a1d2cc21-97e0-45a6-8e56-419468d6029f/bd71225f2b7dad7dc44272d303276e7f/aspnetcore-runtime-3.1.27-linux-x64.tar.gz"
    source_sha256 = "8fc95f7e66168a9ee9fb662c971c61264858e9b0c7aedd8e93b7b1f6fa0a5ed3"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_3.1.27_linux_x64_bionic_89c395e6.tar.xz"
    version = "3.1.27"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:6.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@6.0.6?checksum=38ad01d083f0f493116bd06dd80210589abc8b3d502cf81c5dc40ba0fc19d3d5&download_url=https://download.visualstudio.microsoft.com/download/pr/afd5344f-a9e9-45f9-85b5-de4551c53736/c30996daa407f9bb540ebc5edfcf16fc/aspnetcore-runtime-6.0.6-linux-x64.tar.gz"
    sha256 = "2033eec1c00243664e7909d253ef9d5683c15e8f265c8d7962d4d88ca725fb6d"
    source = "https://download.visualstudio.microsoft.com/download/pr/afd5344f-a9e9-45f9-85b5-de4551c53736/c30996daa407f9bb540ebc5edfcf16fc/aspnetcore-runtime-6.0.6-linux-x64.tar.gz"
    source_sha256 = "38ad01d083f0f493116bd06dd80210589abc8b3d502cf81c5dc40ba0fc19d3d5"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_6.0.6_linux_x64_bionic_2033eec1.tar.xz"
    version = "6.0.6"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:6.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@6.0.7?checksum=61c2b79cc31e1d5df9a398766044177cecb7b9c2baad4ef9d011723ba21fd0ee&download_url=https://download.visualstudio.microsoft.com/download/pr/98271725-1784-407c-841a-64d87c674512/b433af33506c816e3b5838f5c65d990a/aspnetcore-runtime-6.0.7-linux-x64.tar.gz"
    sha256 = "12d798aa1bb80549030372d806214420da74effbcd087205d38bea965e708674"
    source = "https://download.visualstudio.microsoft.com/download/pr/98271725-1784-407c-841a-64d87c674512/b433af33506c816e3b5838f5c65d990a/aspnetcore-runtime-6.0.7-linux-x64.tar.gz"
    source_sha256 = "61c2b79cc31e1d5df9a398766044177cecb7b9c2baad4ef9d011723ba21fd0ee"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_6.0.7_linux_x64_bionic_12d798aa.tar.xz"
    version = "6.0.7"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-aspnetcore"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "6.0.*"
    id = "dotnet-aspnetcore"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
