api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"
  id = "paketo-buildpacks/dotnet-core-aspnet"
  name = "Paketo ASP.NET Core Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "c3650d3646c13e79c2102b2a9487f02cbca61318c0fc03122676a8d322e2f016"
    source = "https://download.visualstudio.microsoft.com/download/pr/c66dd1cb-a5fc-4427-bef4-d55a1da5a5c7/17f733c7b6afe91ef9c91e9f6e170cad/aspnetcore-runtime-2.1.27-linux-x64.tar.gz"
    source_sha256 = "1863027b81a24de56ca2c2a77b96e337606b5fe0d78021e69e19bfde96e2da0a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.27_linux_x64_any-stack_c3650d36.tar.xz"
    version = "2.1.27"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "128e76c17cd73d7f382d9cd6261dddb594cd43f3719c4cfef51df8e844965eae"
    source = "https://download.visualstudio.microsoft.com/download/pr/66483281-5453-4504-9686-f72d1fd357f7/0de98386ca1709bde2b5f2f7df4c80da/aspnetcore-runtime-2.1.28-linux-x64.tar.gz"
    source_sha256 = "573bd4c0af11adfc97e84f7ba2f5045b8263e6608cad1464f8cae6f9975643e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_2.1.28_linux_x64_any-stack_128e76c1.tar.xz"
    version = "2.1.28"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "89db461915e2f49bab0b65bf184180221db6a5e6044a9a1ec9afe0152c1cbad9"
    source = "https://download.visualstudio.microsoft.com/download/pr/c20a5ac5-5174-46b8-a875-b916a416050d/b2ddd212a183260569178d880899bd94/aspnetcore-runtime-3.1.16-linux-x64.tar.gz"
    source_sha256 = "b1a2f61d8a49e2a3ca5eb9daa103b83eb49ea1bcf14914560e601222e94a3022"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.16_linux_x64_any-stack_89db4619.tar.xz"
    version = "3.1.16"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "f6dedb579a283714187a2b3b9d38b583dab58bf6b28cdc39a9656deb94b1a8e2"
    source = "https://download.visualstudio.microsoft.com/download/pr/5f9e644f-4555-4a62-8f92-af1ee9634008/778036941916d560bef6da8899ac88f5/aspnetcore-runtime-3.1.17-linux-x64.tar.gz"
    source_sha256 = "fa4354230a6f905e06bf14d8de760b23f4daba27cd8d0364760fcbbe09f32232"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_3.1.17_linux_x64_any-stack_f6dedb57.tar.xz"
    version = "3.1.17"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "3b214b55ff22deddc42672c3cd590472ba07d901ff594b95e232a7c16a49bd49"
    source = "https://download.visualstudio.microsoft.com/download/pr/d6be94b3-458f-43c4-8bb5-9ba261de8c9c/bbe13b54208d088b5fdf428759b5bc0a/aspnetcore-runtime-5.0.7-linux-x64.tar.gz"
    source_sha256 = "22f9f93b4d6a00e76980918b721f7f62654421d7582d486e830ec478c365707c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_5.0.7_linux_x64_any-stack_3b214b55.tar.xz"
    version = "5.0.7"

  [[metadata.dependencies]]
    id = "dotnet-aspnetcore"
    sha256 = "bcb86ed7bf27a340ddb75ada193e796b87523b6147c315d0ce6fd3ddc34ae408"
    source = "https://download.visualstudio.microsoft.com/download/pr/1b54c42a-4904-419b-8c24-bb2f39d4c8ae/279cd30211d8e5a9abf3129d04b4eb0e/aspnetcore-runtime-5.0.8-linux-x64.tar.gz"
    source_sha256 = "fce507e5e8b30464c8a4890d99d48a6b5f9ae04d0f9b2b7eb9b14b9ed783e55c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-aspnetcore/dotnet-aspnetcore_5.0.8_linux_x64_any-stack_bcb86ed7.tar.xz"
    version = "5.0.8"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
