api = "0.8"

[buildpack]
  description = "A buildpack for installing the appropriate .NET Core ASP.NET version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"
  id = "paketo-buildpacks/dotnet-core-aspnet"
  keywords = ["dotnet", "ASP.NET"]
  name = "Paketo ASP.NET Core Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-aspnet/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:3.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@3.1.25?checksum=9257e8a7db8192b94fe8e125e7cd568267185781261498afcb6b5ae0a7d88762&download_url=https://download.visualstudio.microsoft.com/download/pr/0f50a1fa-5fba-4d48-ae5e-dfa009528c60/d188c4e048b701b01604553167c14c5f/aspnetcore-runtime-3.1.25-linux-x64.tar.gz"
    sha256 = "a059903a7f8b77c633974f2d291325ae195e02ab9bb25ff87749f7c5707189c6"
    source = "https://download.visualstudio.microsoft.com/download/pr/0f50a1fa-5fba-4d48-ae5e-dfa009528c60/d188c4e048b701b01604553167c14c5f/aspnetcore-runtime-3.1.25-linux-x64.tar.gz"
    source_sha256 = "9257e8a7db8192b94fe8e125e7cd568267185781261498afcb6b5ae0a7d88762"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_3.1.25_linux_x64_bionic_a059903a.tar.xz"
    version = "3.1.25"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:3.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@3.1.26?checksum=bbf42127f6c58fe6d02205b7ede4962cf10681a274bbf569d27f7e1e2b153e66&download_url=https://download.visualstudio.microsoft.com/download/pr/6f72adf7-0e78-48ea-85ef-e72a39a1f8a1/1ec0238c236c3757e5628563a329fdc4/aspnetcore-runtime-3.1.26-linux-x64.tar.gz"
    sha256 = "ac024ff660da7f046b9605ff9911851cd91a91f016aaf6ab67fb15efb249f559"
    source = "https://download.visualstudio.microsoft.com/download/pr/6f72adf7-0e78-48ea-85ef-e72a39a1f8a1/1ec0238c236c3757e5628563a329fdc4/aspnetcore-runtime-3.1.26-linux-x64.tar.gz"
    source_sha256 = "bbf42127f6c58fe6d02205b7ede4962cf10681a274bbf569d27f7e1e2b153e66"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_3.1.26_linux_x64_bionic_ac024ff6.tar.xz"
    version = "3.1.26"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:6.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@6.0.5?checksum=95a3cc7c4e7de792e39e40ffda72127ba49a49604b61fee18d50f970c9c1e903&download_url=https://download.visualstudio.microsoft.com/download/pr/a0e9ceb8-04eb-4510-876c-795a6a123dda/6141e57558eddc2d4629c7c14c2c6fa1/aspnetcore-runtime-6.0.5-linux-x64.tar.gz"
    sha256 = "ed864a1a8eb5b7d0afa02891fa3585fe6034661c832409d7a03ff87e21702433"
    source = "https://download.visualstudio.microsoft.com/download/pr/a0e9ceb8-04eb-4510-876c-795a6a123dda/6141e57558eddc2d4629c7c14c2c6fa1/aspnetcore-runtime-6.0.5-linux-x64.tar.gz"
    source_sha256 = "95a3cc7c4e7de792e39e40ffda72127ba49a49604b61fee18d50f970c9c1e903"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_6.0.5_linux_x64_bionic_ed864a1a.tar.xz"
    version = "6.0.5"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:6.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@6.0.6?checksum=38ad01d083f0f493116bd06dd80210589abc8b3d502cf81c5dc40ba0fc19d3d5&download_url=https://download.visualstudio.microsoft.com/download/pr/afd5344f-a9e9-45f9-85b5-de4551c53736/c30996daa407f9bb540ebc5edfcf16fc/aspnetcore-runtime-6.0.6-linux-x64.tar.gz"
    sha256 = "d29d55ccdede1be7577eab91a4ce399f8d2ad7a99528447c7d5eaec48d547c40"
    source = "https://download.visualstudio.microsoft.com/download/pr/afd5344f-a9e9-45f9-85b5-de4551c53736/c30996daa407f9bb540ebc5edfcf16fc/aspnetcore-runtime-6.0.6-linux-x64.tar.gz"
    source_sha256 = "38ad01d083f0f493116bd06dd80210589abc8b3d502cf81c5dc40ba0fc19d3d5"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_6.0.6_linux_x64_bionic_d29d55cc.tar.xz"
    version = "6.0.6"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-aspnetcore"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "6.0.*"
    id = "dotnet-aspnetcore"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
