api = "0.8"

[buildpack]
  description = "A buildpack for installing the appropriate .NET Core ASP.NET version"
  homepage = "https://github.com/paketo-buildpacks/dotnet-core-aspnet"
  id = "paketo-buildpacks/dotnet-core-aspnet"
  keywords = ["dotnet", "ASP.NET"]
  name = "Paketo Buildpack for ASP.NET Core"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dotnet-core-aspnet/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:3.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@3.1.29?checksum=9a5ec546b39e9c9e981c3c27659fcfa9cfd1b25e33ccfdd36432c348641170c0&download_url=https://download.visualstudio.microsoft.com/download/pr/d35c543b-44be-46ab-abf0-de8af9c5b3cb/4a17a6aaabe3f2f0e49de31f2f809713/aspnetcore-runtime-3.1.29-linux-x64.tar.gz"
    sha256 = "48e653bbb0f018157a3223ee78884ff10c8e6e2131b19beb2020d9e04c592e47"
    source = "https://download.visualstudio.microsoft.com/download/pr/d35c543b-44be-46ab-abf0-de8af9c5b3cb/4a17a6aaabe3f2f0e49de31f2f809713/aspnetcore-runtime-3.1.29-linux-x64.tar.gz"
    source_sha256 = "9a5ec546b39e9c9e981c3c27659fcfa9cfd1b25e33ccfdd36432c348641170c0"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_3.1.29_linux_x64_bionic_48e653bb.tar.xz"
    version = "3.1.29"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:3.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-12-13T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@3.1.30?checksum=92e8e028d9a6094437a38ba2d3a7898436f027ccd2655ca52b2b0b27e42e3455&download_url=https://download.visualstudio.microsoft.com/download/pr/12f61df9-e5d2-4cc2-b992-80d30ee3fc43/0087f4e0b8b3a94effa890ee3ebba0b1/aspnetcore-runtime-3.1.30-linux-x64.tar.gz"
    sha256 = "8832421ba6308e392ca9540a02ab3049fbeb74523d3403a1479808efe01624b0"
    source = "https://download.visualstudio.microsoft.com/download/pr/12f61df9-e5d2-4cc2-b992-80d30ee3fc43/0087f4e0b8b3a94effa890ee3ebba0b1/aspnetcore-runtime-3.1.30-linux-x64.tar.gz"
    source_sha256 = "92e8e028d9a6094437a38ba2d3a7898436f027ccd2655ca52b2b0b27e42e3455"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_3.1.30_linux_x64_bionic_8832421b.tar.xz"
    version = "3.1.30"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:6.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@6.0.9?checksum=9e05b2f6d80e50b112064a92b14dd758dd75253303fa7cd86d0c24c1baf92a51&download_url=https://download.visualstudio.microsoft.com/download/pr/1a2bca2e-f525-4ecf-9c46-06889b4ce3a4/1a7ad60df284ca6b00ca5d31cc1b1c7c/aspnetcore-runtime-6.0.9-linux-x64.tar.gz"
    sha256 = "65a8b09c05f8e091c0422c522e9332699dac0263672a6d4ba7589ef4bff03cf8"
    source = "https://download.visualstudio.microsoft.com/download/pr/1a2bca2e-f525-4ecf-9c46-06889b4ce3a4/1a7ad60df284ca6b00ca5d31cc1b1c7c/aspnetcore-runtime-6.0.9-linux-x64.tar.gz"
    source_sha256 = "9e05b2f6d80e50b112064a92b14dd758dd75253303fa7cd86d0c24c1baf92a51"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_6.0.9_linux_x64_bionic_65a8b09c.tar.xz"
    version = "6.0.9"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:6.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-11-12T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@6.0.10?checksum=17685d3e8fa7aa9c1a658f7ca5e176bec7bb4c189b0352ac5abfed98135b93d9&download_url=https://download.visualstudio.microsoft.com/download/pr/7d44ddeb-ad35-41a8-a581-03b151afbd80/6888586c28836b1e1f71df879184550b/aspnetcore-runtime-6.0.10-linux-x64.tar.gz"
    sha256 = "6d47537780c728d3775c9afc03fba25423e9c74c937f436c2700bbfb68f88ff7"
    source = "https://download.visualstudio.microsoft.com/download/pr/7d44ddeb-ad35-41a8-a581-03b151afbd80/6888586c28836b1e1f71df879184550b/aspnetcore-runtime-6.0.10-linux-x64.tar.gz"
    source_sha256 = "17685d3e8fa7aa9c1a658f7ca5e176bec7bb4c189b0352ac5abfed98135b93d9"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_6.0.10_linux_x64_bionic_6d475377.tar.xz"
    version = "6.0.10"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:microsoft:asp.net_core:7.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-05-14T00:00:00Z"
    id = "dotnet-aspnetcore"
    licenses = ["MIT", "MIT-0"]
    name = ".NET Core ASPNet"
    purl = "pkg:generic/dotnet-aspnetcore@7.0.0?checksum=27753c368cc075e23fe2c23063be252f54d19194a004b178b4faab1ba2e8af8d&download_url=https://download.visualstudio.microsoft.com/download/pr/4bbb4d31-70ba-4def-b747-4358be873982/3dbca5b64c2ffb88641c0e42bdeb297a/aspnetcore-runtime-7.0.0-linux-x64.tar.gz"
    sha256 = "4ed44c14ddfe35a19f7744a7d9b9e4e78f697734bad8f2cea8cc5473ffb96f48"
    source = "https://download.visualstudio.microsoft.com/download/pr/4bbb4d31-70ba-4def-b747-4358be873982/3dbca5b64c2ffb88641c0e42bdeb297a/aspnetcore-runtime-7.0.0-linux-x64.tar.gz"
    source_sha256 = "27753c368cc075e23fe2c23063be252f54d19194a004b178b4faab1ba2e8af8d"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/dotnet-aspnetcore/dotnet-aspnetcore_7.0.0_linux_x64_bionic_4ed44c14.tar.xz"
    version = "7.0.0"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "dotnet-aspnetcore"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "6.0.*"
    id = "dotnet-aspnetcore"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "7.0.*"
    id = "dotnet-aspnetcore"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
